# Generated by Django 4.2.2 on 2023-12-18 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_newsstory_image_field_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsstory',
            options={'verbose_name_plural': 'News Stories'},
        ),
        migrations.RenameField(
            model_name='newsstory',
            old_name='image_field',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='Author of the news story', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='Enter your comment here'),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='title',
            field=models.CharField(help_text='Enter the title of the news story', max_length=200),
        ),
    ]
